apiVersion: v1
name: kafka-manager
version: 2.3.0
appVersion: 2.0.0.2
kubeVersion: "^1.8.0-0"
description: A tool for managing Apache Kafka.
home: https://github.com/yahoo/kafka-manager
icon: https://kafka.apache.org/images/logo.png
sources:
  - https://github.com/yahoo/kafka-manager
keywords:
- kafka
- zookeeper
- kafka-manager
maintainers:
- name: giacomoguiulfo
  email: giacomoguiulfo@gmail.com
- name: ssalaues
  email: salim.salaues@scality.com
engine: gotpl
